finalProject/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'page#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get 'page/index'
  get 'page/adminReport'
  get '/page/majorRequirements'
  get 'page/studentComplete'
  get 'page/userReport'
  get 'page/addCourse'
  get 'page/exportData'

  post'page/majorRequirements' => 'page#majorRequirements'
  post'page/studentComplete' => 'page#studentComplete'
  post'page/adminReport' => 'page#userReport'
  post'page/adminReport' => 'page#exportData'
  post'page/addCourse' => 'page#addCourse'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'page#index'
  
  resources :page


end

finalProject/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

finalProject/app/models/course.rb
class Course < ApplicationRecord
    has_many :course_mappings
    has_many :degrees, through: :course_mappings
    has_many :finished_courses
    has_many :finished_courses, through: :finished_courses
end

finalProject/app/models/course_mapping.rb
class CourseMapping < ApplicationRecord
    belongs_to :course
    belongs_to :degree
end

finalProject/app/models/degree.rb
class Degree < ApplicationRecord
    

    has_many :course_mappings
    has_many :courses, through: :course_mappings
    has_many :degree_in_progresses
    has_many :users, through: :degree_in_progresses
end

finalProject/app/models/degree_in_progress.rb
class DegreeInProgress < ApplicationRecord
    belongs_to :user
    belongs_to :degree
end

finalProject/app/models/finished_course.rb
class FinishedCourse < ApplicationRecord
    belongs_to :user
    belongs_to :course
end

finalProject/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #removed :recoverable to disable the "Forgot password?" option
  devise :database_authenticatable, :registerable,
        :rememberable, :validatable, :trackable

    has_many :finished_courses
    has_many :courses, through: :finished_courses
    has_many :degree_in_progresses
    has_many :degrees, through: :degree_in_progresses
end

finalProject/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    layout "layout"
end

finalProject/app/controllers/page_controller.rb
require 'csv'
class PageController < ApplicationController
  before_action :set_values, only: [:show, :edit, :update, :destroy]

  def index
    @DegreeSearch = DegreeInProgress.all
    @DegreeProgress = DegreeInProgress.create(degree_in_progress_params)
  end

  def adminReport
    @Users = User.all
    @report = User.where(params[:user_id])
  end

  def exportData

    response.headers['Content-Type'] = 'text/csv'
    response.headers['Content-Disposition'] = "attachement; filename = report.csv"
    @Mappings = CourseMapping.all
    @Finished = FinishedCourse.all
    @DegreeProgress = DegreeInProgress.all
    @Courses = Course.all
    @report = User.find(params[:user_id])
    render template: "page/exportData.csv.erb", :layout => false
  end

  def userReport
    @Mappings = CourseMapping.all
    @Finished = FinishedCourse.all
    @DegreeProgress = DegreeInProgress.all
    @Courses = Course.all
    @report = User.find(params[:user_id])
  end

  def majorRequirements
    @search = Course.find_by(subCat: params[:category].to_s.upcase)
    @searchRemove = Course.find_by(subCat: params[:categoryRemove].to_s.upcase)
    @Courses = Course.all
    @CourseMapping = CourseMapping.create(course_mappings_params)
    @Mappings = CourseMapping.all
  end

  def studentComplete
    @search = Course.find_by(subCat: params[:category].to_s.upcase)

    @Mappings = CourseMapping.all
    @Finished = FinishedCourse.all
    @DegreeProgress = DegreeInProgress.all
    @Courses = Course.all
    @FinishedCreate = FinishedCourse.create(finished_course_params)
  end

  def addCourse
    @addCourse = Course.new(course_params)

    @Courses = Course.all


    if @addCourse.title.length > 0 && @addCourse.subCat.length > 0 && @addCourse.MaxCH != nil && @addCourse.MinCH != nil 
      check = true
      @Courses.each do |c|
        if c.subCat == @addCourse.subCat
          check = false
        end
      end
      if check
        @addCourse.save
      end
    end

  end

  private
  def course_params
    params.permit(:id, :title, :subCat, :MaxCH, :MinCH)
  end

 private
  def finished_course_params
    params.permit(:id, :user_id, :course_id)
  end

  private
  def degree_in_progress_params
    params.permit(:id, :user_id, :degree_id)
  end

  private
  def course_mappings_params
    params.permit(:id, :course_id, :degree_id)
  end
end

finalProject/app/helpers/application_helper.rb
module ApplicationHelper
end

finalProject/app/helpers/page_helper.rb
module PageHelper

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

finalProject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

finalProject/app/views/layouts/layout.erb
<!DOCTYPE html>
  <html lang= "en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
     <title>Ohio State Courses</title>
     <%= stylesheet_link_tag "page" %>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tarekraafat/autocomplete.js@10.2.7/dist/css/autoComplete.02.min.css">
    
     </head>
    <body>
      <div class= "header" >
        <%= image_tag "osu_logo.png", alt: "osu logo", class: "logo" %>
        <h1>Courses Website</h1>
      </div>
      <div class= "middle">
        <%=  yield %>
      </div>
      <div class= "footer">
        <p class= "authors"> Made in 2022 by: Ben Pearlstein, Matthew Rosivack, Camryn Friedman, Aishwarya Arun, and Yifan Zhou </p>
      </div>
    </body>
    </body>
  </html>

finalProject/app/views/page/addCourse.html.erb
<%= stylesheet_link_tag "addCourse" %>


<nav class= "navbar navbar-expand-sm navbar-light">
<ul class= "navbar-nav">
  <li class = "nav-item"><%= link_to 'Home', page_index_path, :class => "nav-link"%></li>
  <li class= "nav-item"><%= link_to 'Generate Reports', page_adminReport_path, :class => "nav-link" %></li>
  <li class= "nav-item"><%= link_to 'Major Requirements', page_majorRequirements_path, :class => "nav-link" %></li>
  <li class= "nav-item active"><%= link_to 'Add New Course', page_addCourse_path, :class => "nav-link" %></li>
  <li class= "nav-item"><%=link_to "Sign Out", destroy_user_session_path, method: :delete, :class => "nav-link"%></li>

</ul>
</nav>
<div class = "text-center", "alignment">


  <h2 class="text-center">Add Course</h2>

  <%= form_tag(page_addCourse_path) do%>

    <div class="field">
      <label for=":subCat">Catalog Number (ie CSE 2221)</label><br />
      <input id = "subCat" name="subCat" type="text"/ >
    </div>

    <div class="field">
      <label for=":title">Course Title (ie Software I)</label><br />
      <input id = "title" name="title" type="text"/ >
    </div>

    <div class="field">
        <label for=":MinCH">Minimum Credit Hours</label><br />
        <input id = "MinCH" name="MinCH" type="text"/ >
    </div>

    <div class="field">
        <label for=":MaxCH">Maximum Credit Hours</label><br />
        <input id = "MaxCH" name="MaxCH" type="text"/ >
    </div>

    <div class="actions", "button-padding-top">
        <button class="btn btn-primary btn-block button-top" >Add Class</button>
    </div>
  <% end %>
</div>

finalProject/app/views/page/adminReport.html.erb
<%= stylesheet_link_tag "adminReport" %>

<nav class= "navbar navbar-expand-sm navbar-light">
<ul class= "navbar-nav">
  <li class = "nav-item"><%= link_to 'Home', page_index_path, :class => "nav-link"%></li>
  <li class= "nav-item active"><%= link_to 'Generate Reports', page_adminReport_path, :class => "nav-link" %></li>
  <li class= "nav-item"><%= link_to 'Major Requirements', page_majorRequirements_path, :class => "nav-link" %></li>
  <li class= "nav-item"><%= link_to 'Add New Course', page_addCourse_path, :class => "nav-link" %></li>
  <li class= "nav-item"><%=link_to "Sign Out", destroy_user_session_path, method: :delete, :class => "nav-link"%></li>
</ul>
</nav>
<h2 class="text-center">Administrator Report</h2>

<%# <p>Generate a table with users and the courses they have compelted and which ones are still required</p> %>



<table class="center">
<tr>
    <th>Student Email</th>
    <th>Report</th>
    <th>Export</th>
</tr>
    <% @Users.each do |u| %>
        <% if u.id != 1 %>
            <tr>
                <td><%= u.email %></td>
                <td><%= link_to 'Generate Report', page_userReport_path(user_id: u.id) %> </td>
                <td><%= link_to 'Export CSV', page_exportData_path(user_id: u.id) %> </td>
            </tr>
        <%end%>
    <%end%>
</table>

finalProject/app/views/page/exportData.csv.erb
<%= CSV.generate_line(["Completed Courses"]) %>
<%= CSV.generate_line(["Catalog Number", "Title", "Credit Hours"]) %>
<% @DegreeProgress.each do |degree| %>
    <% if degree.user_id == @report.id %>
        <% @Finished.each do |finished| %>
            <% if finished.user_id == @report.id %>
                <% check = false %>
                <% @Mappings.each do |mapping| %>
                    <% if mapping.degree_id == degree.degree_id && mapping.course_id == finished.course_id %>
                        <% check = true %>
                    <%end%>
                <%end%>
                <% if !check %>
                    <% thisCourse = @Courses.find_by(id: finished.course_id) %>
                    <%= CSV.generate_line([thisCourse.subCat, thisCourse.title, thisCourse.MaxCH]) -%>
                <%end%>
            <%end%>
        <%end%>
    <%end%>
<%end%>

<%= CSV.generate_line(['Incomplete Courses']) %>
<%= CSV.generate_line(['Catalog Number', 'Title', 'Credit Hours']) %>
<% @DegreeProgress.each do |degree| %>
    <% if degree.user_id == @report.id %>
        <% @Mappings.each do |mapping| %>
            <% if mapping.degree_id == degree.degree_id %>
                <% check = false %>
                <% @Finished.each do |finished| %>
                    <% if @report.id == finished.user_id && finished.course_id == mapping.course_id %>
                        <% check = true %>
                    <%end%>
                <%end%>
                <% if !check %>
                    <% thisCourse = @Courses.find_by(id: mapping.course_id) %>
                    <%= CSV.generate_line([thisCourse.subCat, thisCourse.title, thisCourse.MaxCH]) -%>
                <%end%>
            <%end%>
        <%end%>
    <%end%>
<%end%>

<%= CSV.generate_line(["Completed Non-Major Courses"]) %>
<%= CSV.generate_line(["Catalog Number", "Title", "Credit Hours"]) %>
<% @DegreeProgress.each do |degree| %>
    <% if degree.user_id == @report.id %>
        <% @Finished.each do |finished| %>
            <% if finished.user_id == @report.id %>
                <% check = false %>
                <% @Mappings.each do |mapping| %>
                    <% if mapping.degree_id == degree.degree_id && mapping.course_id == finished.course_id %>
                        <% check = true %>
                    <%end%>
                <%end%>
                <% if !check %>
                    <% thisCourse = @Courses.find_by(id: finished.course_id) %>
                    <%= CSV.generate_line([thisCourse.subCat, thisCourse.title, thisCourse.MaxCH]) -%>
                <%end%>
            <%end%>
        <%end%>
    <%end%>
<%end%>

finalProject/app/views/page/index.html.erb
<%= stylesheet_link_tag "page" %>
<% if current_user %>
  <div>
    <% if current_user.admin? %>
  
    <nav class= "navbar navbar-expand-sm navbar-light">
    <ul class= "navbar-nav">
      <li class = "nav-item active"><%= link_to 'Home', page_index_path, :class => "nav-link"%></li>
      <li class= "nav-item"><%= link_to 'Generate Reports', page_adminReport_path, :class => "nav-link" %></li>
      <li class= "nav-item"><%= link_to 'Major Requirements', page_majorRequirements_path, :class => "nav-link" %></li>
      <li class= "nav-item"><%= link_to 'Add New Course', page_addCourse_path, :class => "nav-link" %></li>
      <li class= "nav-item"><%=link_to "Sign Out", destroy_user_session_path, method: :delete, :class => "nav-link"%></li>
    </ul>
    </nav>
    <div class="text-center">
    <h2>Welcome</h2>
    <p class= "paragraph">In the navigation bar at the top of the page, you will have 5 options: come back to this Home page, generate a student report, edit major requirements, add a course, and sign out. Below, you can find more information about what each of these does.</p>
    <h3>Home</h3>
    <p class= "paragraph">This will take you back to this page which provides helpful information and instructions about how to use the website.</p>
    <h3>Generate Reports</h3>
    <p class= "paragraph">This will allow you generate a report for any given student and includes their email along with the option to view the report on the website or download it as a .csv file. The report shows completed major courses, incomplete major courses, and completed non-major courses.</p>
    <h3>Major Requirements</h3>
    <p class= "paragraph">On this page, you can adjust the major requirements by adding and removing courses from the curriculum.</p>
    <h3>Add a Course</h3>
    <p class= "paragraph">This page will allow you to manually add a course to the catalog by catalog number, course title, minimum credit hours, and maximum credit hours.</p>
    <h3>Sign Out</h3>
    <p class= "paragraph">This will take you back to the login page</h3>
    </div>
 

    <% else %>
      <% if current_user.sign_in_count == 1 && !current_user.admin %>
        <% check = false %>
        <% @DegreeSearch.each do |degree| %>
          <% if degree.user_id == current_user.id %>
           <% check = true %>
            <%end%>
        <%end%>
        <% if !check %>
          <% DegreeInProgress.create(user_id: current_user.id, degree_id: 1) %>
          <%end%>
        <%end%> 
        <nav class= "navbar navbar-expand-sm navbar-light">
            <ul class= "navbar-nav">
              <li class = "nav-item active"><%= link_to 'Home', page_index_path, :class => "nav-link"%></li>
              <li class = "nav-item"><%= link_to 'Degee Audit', page_studentComplete_path, :class => "nav-link"%></li>
              <li class = "nav-item"><%=link_to "Sign Out", destroy_user_session_path, method: :delete, :class => "nav-link"%></li>
            </ul>
        </nav>
        <div class="text-center">
        <h2>Welcome</h2>

        <p class= "paragraph">In the navigation bar at the top of the page, you will have 3 options: come back to this Home page, generate your degree audit, and sign out. Below, you can find more information about what each of these does.</p>
        <h3>Home</h3>
        <p class= "paragraph">This will take you back to this page which provides helpful information and instructions about how to use the website.</p></br>
        <h3>Degree Audit</h3>
        <p class= "paragraph">Here you will find a list of your completed and incompleted courses. If you see no incomplete courses, make sure to check with your administrator to ensure they have first added courses required for your major.</p></br>
        <h3>Sign Out</h3>
        <p class= "paragraph">This will take you back to the login page</h3>
        </div>
    <%end%>
  
  </div>
<%end%>

finalProject/app/views/page/majorRequirements.html.erb
<%= stylesheet_link_tag "page" %>

<nav class= "navbar navbar-expand-sm navbar-light">
<ul class= "navbar-nav">
  <li class = "nav-item"><%= link_to 'Home', page_index_path, :class => "nav-link"%></li>
  <li class= "nav-item"><%= link_to 'Generate Reports', page_adminReport_path, :class => "nav-link" %></li>
  <li class= "nav-item active"><%= link_to 'Major Requirements', page_majorRequirements_path, :class => "nav-link" %></li>
  <li class= "nav-item"><%= link_to 'Add New Course', page_addCourse_path, :class => "nav-link" %></li>
  <li class= "nav-item"><%=link_to "Sign Out", destroy_user_session_path, method: :delete, :class => "nav-link"%></li>


  </ul>
</nav>
<h2 class="text-center">Major Requirements</h2>
<div class = "text-center", "alignment">
<div class = "entering">
<div class = "center">
<p>Enter a Course to add to the Computer Science Degree</p>

<%= form_tag(page_majorRequirements_path) do %>
    <%= text_field_tag 'category', nil, autocomplete: :off %>
<%end%>

<script src="https://cdn.jsdelivr.net/npm/@tarekraafat/autocomplete.js@10.2.7/dist/autoComplete.min.js"></script>
<script>
    const courseArr = [];
    <% @Courses.each do |course| %>
        courseArr.push("<%= course.subCat %>");
    <%end%>
    const autoCompleteJS = new autoComplete({
        selector: "#category",
        placeHolder: "Example: CSE 3901",
        data: {
            src: courseArr,
            cache: true,
        },
        resultItem: {
            highlight: true
        },
        submit: true,
        events: {
            input: {
                selection: (event) => {
                    const selection = event.detail.selection.value;
                    autoCompleteJS.input.value = selection;
                }
            }
        }
    });
</script>

<% added = 0 %>
<% if @search != nil %>
    <% @Courses.each do |c| %>
        <% if c.subCat == @search.subCat && !CourseMapping.exists?(course_id: c.id) %>
            <p>Successfully added <%= @search.subCat %> as a degree requirement!</p>
            <% added = 1 %>
            <% CourseMapping.create(course_id: c.id, degree_id: 1) %>
        <%end%>
    <%end%>
<%end%>
<% if added == 0 %>
    <% if @search == nil && params[:category] != nil %>
        <p><%= params[:category].to_s.upcase %> does not exist as a course.</p>
    <% elsif @search != nil %>
        <p><%= @search.subCat %> is already a degree requirement!</p>
    <%end%>
<%end%>
</div>


<div class = "center">
<p>Enter a Course to remove from the Computer Science Degree</p>

<%= form_tag(page_majorRequirements_path) do %>
    <div class="autoComplete_wrapper">
    <%= text_field_tag 'categoryRemove', nil, autocomplete: :off, placeholder: "Example: CSE 3901"%>
    </div>
<%end%>

<% remove = 0 %>
<% if @searchRemove != nil %>
    <% @Courses.each do |c| %>
        <% if c.subCat == @searchRemove.subCat && CourseMapping.exists?(course_id: c.id) %>
            <p>Successfully removed <%= @searchRemove.subCat %> as a degree requirement!</p>
            <% remove = 1 %>
            <% CourseMapping.find_by(course_id: c.id, degree_id: 1).destroy %>
        <%end%>
    <%end%>
<%end%>
<% if remove == 0 %>
    <% if @searchRemove == nil && params[:categoryRemove] != nil %>
        <p><%= params[:categoryRemove].to_s.upcase %> does not exist as a course.</p>
    <% elsif @searchRemove != nil %>
        <p><%= @searchRemove.subCat %> is not a degree requirement!</p>
    <%end%>
<%end%>
</div>
</div>
<h3>Courses Required For Major</h3>
<table class="center">
    <tr>
        <th>Catalog Number</th>
        <th>Description</th>
    </tr>
    
    <% @Mappings.each do |mapping| %>
        <% thisCourse = @Courses.find_by(id: mapping.course_id) %>
        <tr>
        <td><%= thisCourse.subCat %></td>
        <td><%= thisCourse.title %></td>
        </tr>
    <%end%>
</table>
</div>

finalProject/app/views/page/studentComplete.html.erb
<%= stylesheet_link_tag "page" %>

<nav class= "navbar navbar-expand-sm navbar-light">
<ul class= "navbar-nav">
  <li class = "nav-item "><%= link_to 'Home', page_index_path, :class => "nav-link"%></li>
  <li class = "nav-item active"><%= link_to 'Degee Audit', page_studentComplete_path, :class => "nav-link"%></li>
  <li class = "nav-item"><%=link_to "Sign Out", destroy_user_session_path, method: :delete, :class => "nav-link"%></li> 

</ul>
</nav>
<h2 class="text-center">Student Degree Audit</h2>
<div class = "text-center", "alignment">
<p>Enter a course that has been completed</p>



<%= form_tag(page_studentComplete_path) do %>
    <%= text_field_tag 'category', nil, autocomplete: :off %>
<% end %>

<script src="https://cdn.jsdelivr.net/npm/@tarekraafat/autocomplete.js@10.2.7/dist/autoComplete.min.js"></script>
<script>
    const courseArr = [];
    <% @Courses.each do |course| %>
        courseArr.push("<%= course.subCat %>");
    <%end%>
    const autoCompleteJS = new autoComplete({
        selector: "#category",
        placeHolder: "Example: CSE 3901",
        data: {
            src: courseArr,
            cache: true,
        },
        resultItem: {
            highlight: true
        },
        submit: true,
        events: {
            input: {
                selection: (event) => {
                    const selection = event.detail.selection.value;
                    autoCompleteJS.input.value = selection;
                }
            }
        }
    });
</script>

<% added = 0 %>
<% if @search != nil %>
    <% @Courses.each do |c| %>
        <% if c.subCat == @search.subCat && !FinishedCourse.exists?(user_id: current_user.id, course_id: c.id) %>
            <p>Successfully added <%= @search.subCat %> as a finished course!</p>
            <% added = 1 %>
            <% FinishedCourse.create(user_id: current_user.id, course_id: c.id) %>
        <%end%>
    <%end%>
<%end%>
<% if added == 0 %>
    <% if @search == nil && params[:category] != nil %>
        <p><%= params[:category].to_s.upcase %> does not exist as a course.</p>
    <% elsif @search != nil %>
        <p>You have already finished <%= @search.subCat %>.</p>
    <%end%>
<%end%>

<h3 class="text-center">Completed Major Courses</h3>
<table class ="center">
    <tr>
        <th>Catalog Number</th>
        <th>Description</th>
    </tr>

    <% @DegreeProgress.each do |degree| %>
        <% if degree.user_id == current_user.id %>
            <% @Mappings.each do |mapping| %>
                <% if mapping.degree_id == degree.degree_id %>
                    <% check = false %>
                    <% @Finished.each do |finished| %>
                        <% if current_user.id == finished.user_id && finished.course_id == mapping.course_id %>
                            <% check = true %>
                        <%end%>
                    <%end%>
                    <% if check %>
                        <% thisCourse = @Courses.find_by(id: mapping.course_id) %>
                        <tr>
                        <td><%= thisCourse.subCat %></td>
                        <td><%= thisCourse.title %></td>
                        </tr>
                    <%end%>
                <%end%>
            <%end%>
        <%end%>
    <%end%>
</table>

<h3 class="text-center">Incomplete Major Courses</h3>
<table class="center">
    <tr>
        <th>Catalog Number</th>
        <th>Description</th>
    </tr>
    
    <% @DegreeProgress.each do |degree| %>
        <% if degree.user_id == current_user.id %>
            <% @Mappings.each do |mapping| %>
                <% if mapping.degree_id == degree.degree_id %>
                    <% check = false %>
                    <% @Finished.each do |finished| %>
                        <% if current_user.id == finished.user_id && finished.course_id == mapping.course_id %>
                            <% check = true %>
                        <%end%>
                    <%end%>
                    <% if !check %>
                        <% thisCourse = @Courses.find_by(id: mapping.course_id) %>
                        <tr>
                        <td><%= thisCourse.subCat %></td>
                        <td><%= thisCourse.title %></td>
                        </tr>
                    <%end%>
                <%end%>
            <%end%>
        <%end%>
    <%end%>
</table>

<h3 class="text-center">Completed Non-Major Courses</h3>
<table class="center">
    <tr>
        <th>Catalog Number</th>
        <th>Description</th>
    </tr>

    <% @DegreeProgress.each do |degree| %>
        <% if degree.user_id == current_user.id %>
            <% @Finished.each do |finished| %>
                <% if finished.user_id == current_user.id %>
                    <% check = false %>
                    <% @Mappings.each do |mapping| %>
                        <% if mapping.degree_id == degree.degree_id && mapping.course_id == finished.course_id %>
                            <% check = true %>
                        <%end%>
                    <%end%>
                    <% if !check %>
                        <% thisCourse = @Courses.find_by(id: finished.course_id) %>
                        <tr>
                        <td><%= thisCourse.subCat %></td>
                        <td><%= thisCourse.title %></td>
                        </tr>
                    <%end%>
                <%end%>
            <%end%>
        <%end%>
    <%end%>
</table>
</div>

finalProject/app/views/page/userReport.html.erb
<%= stylesheet_link_tag "page" %>

<h2 class="text-center">Student Report</h2>

<div class = "text-center", "alignment">
<h3 class="text-center">Completed Major Courses</h3>
<table class="center">
    <tr>
        <th>Catalog Number</th>
        <th>Description</th>
    </tr>

    <% @DegreeProgress.each do |degree| %>
        <% if degree.user_id == @report.id %>
            <% @Mappings.each do |mapping| %>
                <% if mapping.degree_id == degree.degree_id %>
                    <% check = false %>
                    <% @Finished.each do |finished| %>
                        <% if @report.id == finished.user_id && finished.course_id == mapping.course_id %>
                            <% check = true %>
                        <%end%>
                    <%end%>
                    <% if check %>
                        <% thisCourse = @Courses.find_by(id: mapping.course_id) %>
                        <tr>
                        <td><%= thisCourse.subCat %></td>
                        <td><%= thisCourse.title %></td>
                        </tr>
                    <%end%>
                <%end%>
            <%end%>
        <%end%>
    <%end%>

</table>

<h3 class="text-center">Incomplete Major Courses</h3>
<table class = "center">
    <tr>
        <th class="text-center">Catalog Number</th>
        <th class="text-center">Description</th>
    </tr>

    <% @DegreeProgress.each do |degree| %>
        <% if degree.user_id == @report.id %>
            <% @Mappings.each do |mapping| %>
                <% if mapping.degree_id == degree.degree_id %>
                    <% check = false %>
                    <% @Finished.each do |finished| %>
                        <% if @report.id == finished.user_id && finished.course_id == mapping.course_id %>
                            <% check = true %>
                        <%end%>
                    <%end%>
                    <% if !check %>
                        <% thisCourse = @Courses.find_by(id: mapping.course_id) %>
                        <tr>
                        <td><%= thisCourse.subCat %></td>
                        <td><%= thisCourse.title %></td>
                        </tr>
                    <%end%>
                <%end%>
            <%end%>
        <%end%>
    <%end%>

</table>

<h3 class="text-center">Completed Non-Major Courses</h3>
<table class = "center">
    <tr>
        <th>Catalog Number</th>
        <th>Description</th>
    </tr>

    <% @DegreeProgress.each do |degree| %>
        <% if degree.user_id == @report.id %>
            <% @Finished.each do |finished| %>
                <% if finished.user_id == @report.id %>
                    <% check = false %>
                    <% @Mappings.each do |mapping| %>
                        <% if mapping.degree_id == degree.degree_id && mapping.course_id == finished.course_id %>
                            <% check = true %>
                        <%end%>
                    <%end%>
                    <% if !check %>
                        <% thisCourse = @Courses.find_by(id: finished.course_id) %>
                        <tr>
                        <td><%= thisCourse.subCat %></td>
                        <td><%= thisCourse.title %></td>
                        </tr>
                    <%end%>
                <%end%>
            <%end%>
        <%end%>
    <%end%>
</table>

<form action="/page/adminReport">
    <div>
        <button class= "btn btn-primary btn-block button-top">Back to All Reports</button>
    </div>
</form>